//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS_DB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGO_DRIVER
    {
        public int NGO_Driver_Id { get; set; }
        public int NGO_Id { get; set; }
        public int Driver_Id { get; set; }
        public System.DateTime Time_Stamp { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual NGO NGO { get; set; }
    }
}
